version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: radius
      MYSQL_USER: radiususer
      MYSQL_PASSWORD: radiuspassword
    volumes:
      - ./db-data:/var/lib/mysql # persistant data.