---

services:
  db:
    image: simonclr/radmac-db:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: 1
    restart: unless-stopped
    ports:
      - "3306:3306"
      - "8082:8080"  # Database health endpoint
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - webnet
  radius:
    image: simonclr/radmac-radius:test
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "1812:1812/udp"
      - "8083:8080"  # Health endpoint
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - webnet

  app:
    image: simonclr/radmac-app:latest
    env_file:
      - .env
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: simonclr/radmac-nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - webnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"  
    networks:
      - webnet

  watchdog:
    image: simonclr/radmac-watchdog:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./watchdog/watchdog_config.yaml:/watchdog/watchdog_config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    name: webnet