---

services:
  db:
    image: simonclr/radmac-db:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - webnet
  radius:
    image: simonclr/radmac-radius:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "1812:1812/udp"
    restart: unless-stopped
    networks:
      - webnet

  app:
    image: simonclr/radmac-app:latest
    env_file:
      - .env
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - webnet

  nginx:
    image: simonclr/radmac-nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - webnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"  
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: overlay