---

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        TIMEZONE: ${APP_TIMEZONE}
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: unless-stopped