# Test Watchdog Configuration for Local Docker Compose Testing
# This config tests restart functionality in a single-host environment

version: 1.3.0

services:
  app:
    health_url: http://test-app:8080/health
    interval_env: WATCHDOG_CHECK_INTERVAL_APP
    default_interval: 15
    actions: [log, restart]  # Testing restart functionality
  database:
    health_url: http://test-db:8080/health
    interval_env: WATCHDOG_CHECK_INTERVAL_DATABASE
    default_interval: 15
    actions: [log, restart]  # Testing restart functionality

# Test Notes:
# - Using shorter intervals (15s) for faster testing
# - Only testing 'log' and 'restart' actions
# - Container names are predictable: test-app, test-db
# - This tests if restart works in single-host Docker environment
