# RadMac Watchdog Configuration - Standard MariaDB Compatible
# Use this if you want to keep standard MariaDB without health endpoint
version: 1.2.3

services:
  app:
    health_url: http://app:8080/health
    interval_env: WATCHDOG_CHECK_INTERVAL_APP
    default_interval: 30
    actions: [log, email, discord, pushbullet, slack, teams, telegram, webhook]
  database:
    # For standard MariaDB, we'll monitor the app's database connectivity instead
    health_url: http://app:8080/health
    interval_env: WATCHDOG_CHECK_INTERVAL_DATABASE
    default_interval: 30
    actions: [log, email, slack, webhook]
  radius:
    health_url: http://radius:8080/health
    interval_env: WATCHDOG_CHECK_INTERVAL_RADIUS
    default_interval: 30
    actions: [log, telegram, webhook]

# Note: This config monitors database health through the app's health endpoint
# since standard MariaDB doesn't have its own health endpoint
